
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - JIRA_SERVER=${JIRA_SERVER}
      - JIRA_USERNAME=${JIRA_USERNAME}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - CONFLUENCE_SERVER=${CONFLUENCE_SERVER}
      - TRELLO_KEY=${TRELLO_KEY}
      - TRELLO_TOKEN=${TRELLO_TOKEN}
      - TRELLO_BOARD_IDS=${TRELLO_BOARD_IDS}
      - SIEM_EXPORT_MODE=${SIEM_EXPORT_MODE}
      - SIEM_EXPORT_DIR=${SIEM_EXPORT_DIR}
      - SIEM_HTTP_URL=${SIEM_HTTP_URL}
      - SIEM_HTTP_TOKEN=${SIEM_HTTP_TOKEN}
      - SIEM_HTTP_AUTH_SCHEME=${SIEM_HTTP_AUTH_SCHEME}
      - SIEM_HTTP_DEBUG=${SIEM_HTTP_DEBUG}
      - JIRA_DEFAULT_PROJECT=${JIRA_DEFAULT_PROJECT}
      - JIRA_ISSUE_TYPE=${JIRA_ISSUE_TYPE}
      - JIRA_CREATE_ON_DETECT=${JIRA_CREATE_ON_DETECT}
      - JIRA_MIN_SEVERITY=${JIRA_MIN_SEVERITY}
      - GLPI_URL=${GLPI_URL}
      - GLPI_APP_TOKEN=${GLPI_APP_TOKEN}
      - GLPI_USER_TOKEN=${GLPI_USER_TOKEN}
      - GLPI_ENTITY_ID=${GLPI_ENTITY_ID}
      - GLPI_CREATE_ON_DETECT=${GLPI_CREATE_ON_DETECT}
      - GLPI_MIN_SEVERITY=${GLPI_MIN_SEVERITY}
      - SLACK_WEBHOOK_ENABLED=${SLACK_WEBHOOK_ENABLED}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - SLACK_WEBHOOK_ROUTING=${SLACK_WEBHOOK_ROUTING}
      - INTEGRATIONS_API_KEYS=${INTEGRATIONS_API_KEYS}
      - INTEGRATIONS_BASE_URL=${INTEGRATIONS_BASE_URL}
      - EXPORT_MODE=${EXPORT_MODE}
      - MS_TENANT_ID=${MS_TENANT_ID}
      - MS_CLIENT_ID=${MS_CLIENT_ID}
      - MS_CLIENT_SECRET=${MS_CLIENT_SECRET}
      - TEAMS_INCLUDE_CHATS=${TEAMS_INCLUDE_CHATS}
      - TEAMS_PAGE_SIZE=${TEAMS_PAGE_SIZE}
      - TEAMS_MAX_PAGES=${TEAMS_MAX_PAGES}
      - TEAMS_FULL_ON_EMPTY=${TEAMS_FULL_ON_EMPTY}
      - TEAMS_BACKFILL_LIMIT=${TEAMS_BACKFILL_LIMIT}
      - API_BASE_URL=${API_BASE_URL}
    restart: unless-stopped
    ports: ["8000:8000"]
    volumes:
      - ./exports:/exports
    depends_on: [mongo]

volumes:
  mongo_data:
